package form;
import koneksi.Koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;/**
 *
 * @author Lenovo
 */
public class FormLaporan extends javax.swing.JFrame {

     Connection conn = Koneksi.getKoneksi();

    public FormLaporan() {
        initComponents();
        setLocationRelativeTo(null);
    }
// ================= LAPORAN ABSENSI =================
    private void tampilAbsensi() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Tanggal");
        model.addColumn("Status");

        try {
            String sql = "SELECT nama, tanggal, status "
                       + "FROM absensi a JOIN pegawai p "
                       + "ON a.id_pegawai = p.id_pegawai";

            ResultSet rs = conn.createStatement().executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                });
            }
            tableLaporan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
// ================= LAPORAN CUTI =================
    private void tampilCuti() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Mulai");
        model.addColumn("Selesai");
        model.addColumn("Jenis");

        try {
            String sql = "SELECT nama, tgl_mulai, tgl_selesai, jenis_cuti "
                       + "FROM cuti c JOIN pegawai p "
                       + "ON c.id_pegawai = p.id_pegawai";

            ResultSet rs = conn.createStatement().executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                });
            }
            tableLaporan.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
// ================= EXPORT =================
    private void exportData() {
        String[] pilihan = {"PDF", "Word", "Excel"};
        int pilih = JOptionPane.showOptionDialog(
                this,
                "Pilih format export",
                "Export Laporan",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                pilihan,
                pilihan[0]
        );

        if (pilih == 0) {
            JOptionPane.showMessageDialog(this, "Export PDF berhasil (simulasi)");
        } else if (pilih == 1) {
            JOptionPane.showMessageDialog(this, "Export Word berhasil (simulasi)");
        } else if (pilih == 2) {
            JOptionPane.showMessageDialog(this, "Export Excel berhasil (simulasi)");
        }
    }

    // ================= IMPORT =================
    private void importData() {
        JFileChooser fc = new JFileChooser();
        int hasil = fc.showOpenDialog(this);

        if (hasil == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            JOptionPane.showMessageDialog(this,
                    "Import dari file:\n" + file.getName() +
                    "\n(Simulasi – Excel)");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLaporan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLaporanAbsensi = new javax.swing.JButton();
        btnLaporanCuti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLaporan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblLaporan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLaporan.setText("LAPORAN ABSENSI & CUTI");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLaporanAbsensi.setBackground(new java.awt.Color(204, 255, 204));
        btnLaporanAbsensi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLaporanAbsensi.setText("Laporan Absensi ");
        btnLaporanAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanAbsensiActionPerformed(evt);
            }
        });

        btnLaporanCuti.setBackground(new java.awt.Color(255, 102, 102));
        btnLaporanCuti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLaporanCuti.setText("Laporan Cuti");
        btnLaporanCuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanCutiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnLaporanAbsensi)
                .addGap(50, 50, 50)
                .addComponent(btnLaporanCuti)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaporanAbsensi)
                    .addComponent(btnLaporanCuti))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableLaporan);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnImport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/import.png"))); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/export.png"))); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnImport)
                .addGap(43, 43, 43)
                .addComponent(btnExport)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(btnExport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblLaporan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importData();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        exportData();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnLaporanAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanAbsensiActionPerformed
      tampilAbsensi();
    }//GEN-LAST:event_btnLaporanAbsensiActionPerformed

    private void btnLaporanCutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanCutiActionPerformed
        tampilCuti();
    }//GEN-LAST:event_btnLaporanCutiActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnLaporanAbsensi;
    private javax.swing.JButton btnLaporanCuti;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLaporan;
    private javax.swing.JTable tableLaporan;
    // End of variables declaration//GEN-END:variables
}
