package form;
import koneksi.Koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class FormAbsensi extends javax.swing.JFrame {

    
   // ================= ATRIBUT =================
    private Connection conn = Koneksi.getKoneksi();
    private DefaultTableModel model;
    private int idAbsensiTerpilih = 0;

    // ================= CONSTRUCTOR =================
    public FormAbsensi() {
        initComponents();
        isiPegawai();
        tampilData();
        setTanggalOtomatis();
        new javax.swing.Timer(1000, e -> setTanggalOtomatis()).start();
    }

    // ================= UTIL =================
    private void setTanggalOtomatis() {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter fmt =
                DateTimeFormatter.ofPattern("dd-MM-yyyy | HH:mm:ss");
        lblTanggalOtomatis.setText("Hari ini : " + now.format(fmt));
    }

    private int getIdPegawai() {
        String data = cbPegawai.getSelectedItem().toString();
        return Integer.parseInt(data.split(" - ")[0]);
    }

    private void resetForm() {
        cbPegawai.setSelectedIndex(0);
        cbStatus.setSelectedIndex(0);
        idAbsensiTerpilih = 0;
    }

    private String menitKeJam(int menit) {
        int jam = menit / 60;
        int sisa = menit % 60;
        return String.format("%02d:%02d", jam, sisa);
    }

    // ================= ISI COMBO =================
    private void isiPegawai() {
        cbPegawai.removeAllItems();
        try {
            String sql = "SELECT id_pegawai, nama FROM pegawai";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cbPegawai.addItem(
                        rs.getInt("id_pegawai") + " - " + rs.getString("nama")
                );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // ================= CEGAH ABSEN DOBEL =================
    private boolean sudahAbsenHariIni(int idPegawai) {
        try {
            String sql =
            "SELECT COUNT(*) FROM absensi " +
            "WHERE id_pegawai = ? " +
            "AND DATE(tanggal) = CURDATE()";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, idPegawai);
            ResultSet rs = pst.executeQuery();
            return rs.next() && rs.getInt(1) > 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return false;
    }

    // ================= HITUNG TERLAMBAT =================
    private int hitungMenitTerlambat() {
        try {
            String sql =
            "SELECT TIMESTAMPDIFF(MINUTE, " +
            "CONCAT(CURDATE(),' 08:00:00'), NOW()) AS terlambat";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                return Math.max(rs.getInt("terlambat"), 0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return 0;
    }

    // ================= TAMPIL DATA =================
    private void tampilData() {
        model = new DefaultTableModel(new String[]{
            "ID", "Nama", "Tanggal", "Status", "Kehadiran", "Terlambat (Jam)"
        }, 0);

        try {
            String sql =
            "SELECT a.id_absensi, p.nama, a.tanggal, a.status, " +
            "IFNULL(a.status_hadir,'-'), " +
            "IFNULL(a.menit_terlambat,0) " +
            "FROM absensi a " +
            "JOIN pegawai p ON a.id_pegawai = p.id_pegawai " +
            "ORDER BY a.tanggal DESC";

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getTimestamp(3),
                    rs.getString(4),
                    rs.getString(5),
                    menitKeJam(rs.getInt(6))
                });
            }

            jTable1.setModel(model);
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormAbsensi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPegawai = new javax.swing.JLabel();
        cbPegawai = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnSave1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTanggalOtomatis = new javax.swing.JLabel();
        tableAbsensi = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        lblDataAbsensi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFormAbsensi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFormAbsensi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormAbsensi.setText("FORM ABSENSI");
        lblFormAbsensi.setFocusable(false);
        lblFormAbsensi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPegawai.setText("Pegawai");
        jPanel1.add(lblPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        cbPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 13, -1, -1));

        lblStatus.setText("Status");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, -1, -1));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Izin", "Sakit", "Alpha" }));
        jPanel1.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 44, 56, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/save.png"))); // NOI18N
        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 114, -1));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 2, 114, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 2, 114, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 2, 114, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTanggalOtomatis.setText("Tanggal Otomatis");
        jPanel3.add(lblTanggalOtomatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        tableAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAbsensiMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAbsensi.setViewportView(jTable1);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel6.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/search_icon-icons.com_52389.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel6.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 73, -1));

        jLabel6.setText("Kategori");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pegawai", "Status", "Tanggal" }));
        jPanel6.add(cbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, -1));
        jPanel6.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, -1));

        lblDataAbsensi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDataAbsensi.setText("DATA ABSENSI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tableAbsensi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(lblFormAbsensi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(lblDataAbsensi)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblFormAbsensi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataAbsensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    tampilData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Tanggal");
    model.addColumn("Status");

    try {
        String kategori = cbKategori.getSelectedItem().toString();
        String keyword = txtSearch.getText();

        String sql = "SELECT a.id_absensi, p.nama, a.tanggal, a.status "
                   + "FROM absensi a JOIN pegawai p "
                   + "ON a.id_pegawai=p.id_pegawai ";

        if (kategori.equals("Pegawai")) {
            sql += "WHERE p.nama LIKE '%"+keyword+"%'";
        } else if (kategori.equals("Status")) {
            sql += "WHERE a.status LIKE '%"+keyword+"%'";
        } else {
            sql += "WHERE a.tanggal LIKE '%"+keyword+"%'";
        }

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_absensi"),
                rs.getString("nama"),
                rs.getDate("tanggal"),
                rs.getString("status")
            });
        }

        jTable1.setModel(model);

        // sembunyikan ID
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAbsensiMouseClicked
        int row = jTable1.getSelectedRow();

    idAbsensiTerpilih = Integer.parseInt(
        jTable1.getValueAt(row, 0).toString()
    );

    cbStatus.setSelectedItem(
        jTable1.getValueAt(row, 3).toString()
    );
    }//GEN-LAST:event_tableAbsensiMouseClicked

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
         if (cbPegawai.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Pegawai belum dipilih!");
        return;
    }

    int idPegawai = getIdPegawai();

    // Cegah absen dobel
    if (sudahAbsenHariIni(idPegawai)) {
        JOptionPane.showMessageDialog(this,
            "Pegawai ini sudah absen hari ini!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    int menitTerlambat = hitungMenitTerlambat();
    String statusHadir = (menitTerlambat > 0) ? "TERLAMBAT" : "HADIR";

    try {
        String sql = "INSERT INTO absensi "
                   + "(id_pegawai, tanggal, status, status_hadir, menit_terlambat) "
                   + "VALUES (?, NOW(), ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idPegawai);
        pst.setString(2, cbStatus.getSelectedItem().toString());
        pst.setString(3, statusHadir);
        pst.setInt(4, menitTerlambat);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
            "Absensi berhasil\n"
          + "Status: " + statusHadir +
            (menitTerlambat > 0 ? "\nTerlambat: " + menitTerlambat + " menit" : "")
        );

        tampilData();
        resetForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         if (idAbsensiTerpilih == 0) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    try {
        String sql = "UPDATE absensi SET status=? WHERE id_absensi=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, cbStatus.getSelectedItem().toString());
        pst.setInt(2, idAbsensiTerpilih);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Absensi berhasil diupdate");

        tampilData();
        resetForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (idAbsensiTerpilih == 0) {
        JOptionPane.showMessageDialog(this, "Pilih data dulu!");
        return;
    }

    int jawab = JOptionPane.showConfirmDialog(
        this, "Hapus data absensi ini?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

    if (jawab == JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM absensi WHERE id_absensi=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, idAbsensiTerpilih);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Absensi berhasil dihapus");

            tampilData();
            resetForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbPegawai;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDataAbsensi;
    private javax.swing.JLabel lblFormAbsensi;
    private javax.swing.JLabel lblPegawai;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTanggalOtomatis;
    private javax.swing.JScrollPane tableAbsensi;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
