package form;

import javax.swing.*;
 
public class MenuUtama extends javax.swing.JFrame {

    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jData = new javax.swing.JMenu();
        menuPegawai = new javax.swing.JMenuItem();
        menuAbsensi = new javax.swing.JMenuItem();
        menuCuti = new javax.swing.JMenuItem();
        jLaporan = new javax.swing.JMenu();
        menuLaporan = new javax.swing.JMenuItem();
        jExit = new javax.swing.JMenu();
        MenuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SISTEM KEPEGAWAIAN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Icons/menuutama.png"))); // NOI18N
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jData.setText("Data");

        menuPegawai.setText("Pegawai");
        menuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPegawaiActionPerformed(evt);
            }
        });
        jData.add(menuPegawai);

        menuAbsensi.setText("Absensi");
        menuAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbsensiActionPerformed(evt);
            }
        });
        jData.add(menuAbsensi);

        menuCuti.setText("Cuti");
        menuCuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCutiActionPerformed(evt);
            }
        });
        jData.add(menuCuti);

        jMenuBar1.add(jData);

        jLaporan.setText("Laporan");

        menuLaporan.setText("Laporan Absensi&Cuti");
        menuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanActionPerformed(evt);
            }
        });
        jLaporan.add(menuLaporan);

        jMenuBar1.add(jLaporan);

        jExit.setText("Exit");

        MenuKeluar.setText("Keluar");
        MenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKeluarActionPerformed(evt);
            }
        });
        jExit.add(MenuKeluar);

        jMenuBar1.add(jExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPegawaiActionPerformed
        FormPegawai pegawai = new FormPegawai();
        pegawai.setVisible(true);
        pegawai.setLocationRelativeTo(null); 
    }//GEN-LAST:event_menuPegawaiActionPerformed

    private void menuAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbsensiActionPerformed
        FormAbsensi absensi = new FormAbsensi();
        absensi.setVisible(true);
        absensi.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuAbsensiActionPerformed

    private void menuCutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCutiActionPerformed
        FormCuti cuti = new FormCuti();
         cuti.setVisible(true);
         cuti.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuCutiActionPerformed

    private void menuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanActionPerformed
       FormLaporan laporan = new FormLaporan();
        laporan.setVisible(true);
        laporan.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuLaporanActionPerformed

    private void MenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKeluarActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin keluar?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
    if(pilihan == JOptionPane.YES_OPTION){
        System.exit(0);
    }
    }//GEN-LAST:event_MenuKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuKeluar;
    private javax.swing.JMenu jData;
    private javax.swing.JMenu jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jLaporan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAbsensi;
    private javax.swing.JMenuItem menuCuti;
    private javax.swing.JMenuItem menuLaporan;
    private javax.swing.JMenuItem menuPegawai;
    // End of variables declaration//GEN-END:variables
}
